# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_identifier', models.CharField(default='inner_identifier', max_length=6, unique=True)),
                ('program_name', models.CharField(default='name', max_length=200)),
                ('added_date', models.CharField(default='added_date', max_length=15)),
            ],
            options={
                'ordering': ('inner_identifier', 'program_name', 'added_date'),
            },
        ),
    ]
