# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hpradiotracker', '0002_radioprogram_have_been_seen_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgramDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpradiotracker.RadioProgram')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('radio_program_id', 'user_id'),
            },
        ),
    ]
