# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_sentmessage_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='sent date'),
        ),
    ]
